### ISSUE TITLE
Add e2e test to circleCI

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#2826]
Add the new e2e tests to run on the circleCI 
Test out on numerous forks to make sure no issues..

**Comment by britt6612** [comment]
1/27 Update

Started a draft PR with the additions for the circle ci tests
as of now, they are not running so going to look today at having one `script` that will allow the project to run and then run tests.

**Comment by britt6612** [comment]
2/3 

config file 


Made a simple app and then added a config file to run tests on circle ci they are running correctly but not showing a summary.

```
version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          command: npm run test
      - store_test_results:
          path: /tmp/test-results
workflows:
  e2e-test:
    jobs:
      - test
```

<img width="908" alt="Screen Shot 2023-02-03 at 10 23 36 AM" src="https://user-images.githubusercontent.com/42451602/216667287-395cdb1e-3632-4259-98b7-2ea7fb543eab.png">

steps are showing that they are getting written: 
<img width="879" alt="Screen Shot 2023-02-03 at 10 23 49 AM" src="https://user-images.githubusercontent.com/42451602/216667350-2610ce80-771e-467d-8494-6a93dd00abce.png">
